trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

jobs:
# -------------------------------------------------------------
# JOB 1: Compilar y Empaquetar el Backend (Express)
# -------------------------------------------------------------
- job: BuildBackend
  displayName: 'Compilar Backend (Express)'
  steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '20.x'
    displayName: 'Instalar Node.js v20'

  - script: |
      cd Memento-API
      npm ci
    displayName: 'Instalar dependencias del Backend'

  - task: ArchiveFiles@2
    inputs:
      rootFolderOrFile: 'Memento-API'
      includeRootFolder: false
      archiveType: 'zip'
      archiveFile: '$(Build.ArtifactStagingDirectory)/api-build.zip'
    displayName: 'Comprimir archivos del Backend'

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)/api-build.zip'
      ArtifactName: 'drop-backend'
    displayName: 'Publicar Artefacto Backend'

# -------------------------------------------------------------
# JOB 2: Compilar y Empaquetar el Frontend (React Web)
# -------------------------------------------------------------
- job: BuildFrontend
  displayName: 'Compilar Frontend (React)'
  steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '20.x'
    displayName: 'Instalar Node.js v20'

  - script: |
      cd Memento-App
      npm ci
      npm run build
    displayName: 'Instalar dependencias y Compilar Vite'

  - task: ArchiveFiles@2
    inputs:
      rootFolderOrFile: 'Memento-App/dist'
      includeRootFolder: false
      archiveType: 'zip'
      archiveFile: '$(Build.ArtifactStagingDirectory)/web-dist.zip'
    displayName: 'Comprimir carpeta dist del Frontend'

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)/web-dist.zip'
      ArtifactName: 'drop-frontend-web'
    displayName: 'Publicar Artefacto Frontend'