trigger:
  branches:
    include:
      - main
  paths:
    include:
      - Memento-API/**

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '20.x'
  displayName: 'Instalar Node.js v20'

- script: |
    cd Memento-API
    npm ci
  displayName: 'Instalar dependencias del Backend'

# Opcional: Publicar artefacto para despliegue en Azure App Service o Render
- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: 'Memento-API'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/api-build.zip'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/api-build.zip'
    ArtifactName: 'drop-backend'
  displayName: 'Guardar artefacto Backend'